trigger:
  - master
variables:
  - group: Common
jobs:
  - job: Linux
    pool:
        vmImage: ubuntu-18.04
    workspace:
        clean: all
    steps:
      - script: $(Build.SourcesDirectory)/build.sh -o DeepSea-libs-linux.tar.gz
        workingDirectory: $(Build.BinariesDirectory)
        displayName: Build
      - publish: $(Build.BinariesDirectory)/DeepSea-libs-linux.tar.gz
        artifact: Linux
        displayName: Publish
  - job: Android
    pool:
        vmImage: ubuntu-latest
    workspace:
        clean: all
    strategy:
        matrix:
            arm32:
                platform: armeabi-v7a
            arm64:
                platform: arm64-v8a
            x86:
                platform: x86
            x86_64:
                platform: x86_64
    steps:
      - script: |
            $(Build.SourcesDirectory)/build.sh -p android \
                --android-ndk $ANDROID_HOME/ndk-bundle --android-abi $(platform) \
                -o DeepSea-libs-android-$(platform).tar.gz
        workingDirectory: $(Build.BinariesDirectory)
        displayName: Build
      - publish: $(Build.BinariesDirectory)/DeepSea-libs-android-$(platform).tar.gz
        artifact: Android $(platform)
        displayName: Publish
  - job: Mac
    pool:
        vmImage: macOS-latest
    strategy:
        matrix:
            arm64:
                platform: arm64
                name-postfix: -arm64
            x86_64:
                platform: x86_64
                name-postfix: -x86_64
            universal:
                platform: arm64;x86_64
                name-postfix: ""
    workspace:
        clean: all
    steps:
      - script: |
            $(Build.SourcesDirectory)/build.sh -DCMAKE_OSX_DEPLOYMENT_TARGET=10.11 \
                -DCMAKE_OSX_ARCHITECTURES="$(platform)" -o DeepSea-libs-mac$(name-postfix).tar.gz
        workingDirectory: $(Build.BinariesDirectory)
        displayName: Build
      - publish: $(Build.BinariesDirectory)/DeepSea-libs-mac$(name-postfix).tar.gz
        artifact: Mac $(platform)
        displayName: Publish
  - job: iOS
    pool:
        vmImage: macOS-latest
    workspace:
        clean: all
    steps:
      - script: |
            $(Build.SourcesDirectory)/build.sh -p ios -o DeepSea-libs-ios.tar.gz
        workingDirectory: $(Build.BinariesDirectory)
        displayName: Build
      - publish: $(Build.BinariesDirectory)/DeepSea-libs-ios.tar.gz
        artifact: iOS
        displayName: Publish
  - job: Windows
    pool:
        vmImage: windows-2019
    workspace:
        clean: all
    strategy:
        matrix:
            win32:
                platform: win32
            win64:
                platform: win64
    steps:
      - script: $(Build.SourcesDirectory)\build.bat -p $(platform) -T v140 -o DeepSea-libs-$(platform).zip
        workingDirectory: $(Build.BinariesDirectory)
        displayName: Build
      - publish: $(Build.BinariesDirectory)\DeepSea-libs-$(platform).zip
        artifact: Windows $(platform)
        displayName: Publish

# vim: ts=4 sts=4 sw=4 et
